disableKinds = ["taxonomy","taxonomyTerm"]

languageCode = 'nb-NO'
title = 'Balevik IT & Service'
theme = 'balevikit-tailwindcss-hugo-theme'

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 30
  resampleFilter = 'CatmullRom'

[params]
  email = "andreasbalevik@gmail.com"
  orgnr = "925316504"

