disableKinds = ["taxonomy","taxonomyTerm"]

languageCode = 'nb-NO'
title = 'Balevik IT & Service'
theme = 'balevikit-tailwindcss-hugo-theme'

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 30
  resampleFilter = 'CatmullRom'

[params]
  email = "andreasbalevik@gmail.com"
  orgnr = "925316504"
  description = "Balevik IT tilbyr enkle og billige nettsider for små bedrifter"
  logo = "path"
  keywords = "Balevik IT, enkle, nettsider, vestland, sogndal, billige"

